---
title: "WQD7004 Group Project - Group 9"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    toc_depth: 3
    number_sections: true
    theme: spacelab
---

# Introduction
This is introduction

# Objectives

# Methodology

## Data Understanding

```{r include = FALSE, warning = FALSE}
# load library
library(stringr)
library(dplyr)
library(data.table)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(ggrepel)
library(GGally)
library(vip)
library(patchwork)
library(magrittr)

# read csv
airline_df <- read.csv("Airline Passenger Satisfaction Dataset\\train_unclean.csv"
                       , header = TRUE
                       , stringsAsFactors = TRUE)

# display dataframe
head(airline_df)

# data dimension
dim(airline_df)

# data class
sapply(airline_df, class)

# summary statistics
summary(airline_df)
```

## Data Cleaning

```{r include = FALSE, warning = FALSE}
# check duplicate
dim(airline_df[duplicated(airline_df$id),])[1]
# no duplicate

# check NA count in each column
colSums(is.na(airline_df))
# Departure.Delay.in.Minutes: 92
# Arrival.Delay.in.Minutes: 310

# check distinct values for each categorical column
levels(airline_df$Gender)
levels(airline_df$Customer.Type)
levels(airline_df$Type.of.Travel)
levels(airline_df$Class)
```

```{r include = FALSE, warning = FALSE}
# data cleaning
# convert gender and customer type into proper case
airline_df$Gender.C = as.factor(str_to_title(airline_df$Gender))
levels(airline_df$Gender)
airline_df$Customer.Type.C = as.factor(str_to_title(airline_df$Customer.Type))
levels(airline_df$Customer.Type)

# clean type of travel
airline_df$Type.of.Travel.C <- 
  ifelse(grepl('^b', airline_df$Type.of.Travel, ignore.case = TRUE), 
         "Business Travel",
         "Personal Travel")
airline_df$Type.of.Travel.C <- as.factor(airline_df$Type.of.Travel.C)
levels(airline_df$Type.of.Travel.C)

# clean class
airline_df$Class.C <- 
  ifelse(grepl('^b', airline_df$Class, ignore.case = TRUE), 
         "Business",
         ifelse(grepl('^(ekon|econ|Eco$)', airline_df$Class, ignore.case = TRUE),
                "Eco",
                "Eco Plus")
         )
airline_df$Class.C <- as.factor(airline_df$Class.C)
levels(airline_df$Class.C)

# clean inflight wifi service rating
# set ratings above 5 as NA and replace with mean exclude 0
airline_df$Inflight.wifi.service.C <- airline_df$Inflight.wifi.service
airline_df$Inflight.wifi.service.C[airline_df$Inflight.wifi.service.C > 5] <- NA
airline_df$Inflight.wifi.service.C[is.na(airline_df$Inflight.wifi.service.C)] <-
  mean(airline_df$Inflight.wifi.service.C
       [airline_df$Inflight.wifi.service.C > 0]
       , na.rm = TRUE
       )
# convert to integer
airline_df$Inflight.wifi.service.C <- 
  round(airline_df$Inflight.wifi.service.C)

# clean food and drink rating
# set ratings above 5 as NA and replace with mean exclude 0
airline_df$Food.and.drink.C <- airline_df$Food.and.drink
airline_df$Food.and.drink.C[airline_df$Food.and.drink.C > 5] <- NA
airline_df$Food.and.drink.C[is.na(airline_df$Food.and.drink.C)] <-
  mean(airline_df$Food.and.drink.C
       [airline_df$Food.and.drink.C > 0]
       , na.rm = TRUE
       )
# convert to integer
airline_df$Food.and.drink.C <- 
  round(airline_df$Food.and.drink.C)

# clean seat comfort
# set ratings above 5 as NA and replace with mean exclude 0
airline_df$Seat.comfort.C <- airline_df$Seat.comfort
airline_df$Seat.comfort.C[airline_df$Seat.comfort.C > 5] <- NA
airline_df$Seat.comfort.C[is.na(airline_df$Seat.comfort.C)] <-
  mean(airline_df$Seat.comfort.C
       [airline_df$Seat.comfort.C > 0]
       , na.rm = TRUE
       )
# convert to integer
airline_df$Seat.comfort.C <- 
  round(airline_df$Seat.comfort.C)

# convert all ratings column to ordinal factor
ratings <- c("Inflight.wifi.service.C", "Food.and.drink.C", "Seat.comfort.C",
          "Departure.Arrival.time.convenient",	"Ease.of.Online.booking",
          "Gate.location", "Online.boarding", "Inflight.entertainment",
          "On.board.service",	"Leg.room.service",	"Baggage.handling",
          "Checkin.service",	"Inflight.service",	"Cleanliness"
          )
airline_df[ratings] <- lapply(airline_df[ratings], 
                              factor, 
                              levels=c(0, 1, 2, 3, 4, 5)
                              )

# replace NA with 0
# Departure & Arrival delay in minutes
delay_cols <- c("Departure.Delay.in.Minutes", "Arrival.Delay.in.Minutes")
airline_df[delay_cols][is.na(airline_df[delay_cols])] <- 0

# rearrange columns
col_order <- c("X", "id", "Gender", "Gender.C", "Customer.Type",
               "Customer.Type.C", "Age", "Type.of.Travel", "Type.of.Travel.C",
               "Class", "Class.C","Flight.Distance", "Inflight.wifi.service", 
               "Inflight.wifi.service.C", "Departure.Arrival.time.convenient",	
               "Ease.of.Online.booking", "Gate.location", "Food.and.drink",
               "Food.and.drink.C", "Online.boarding", "Seat.comfort", 
               "Seat.comfort.C", "Inflight.entertainment", "On.board.service",	
               "Leg.room.service", "Baggage.handling", "Checkin.service",	
               "Inflight.service",	"Cleanliness", "Departure.Delay.in.Minutes",
               "Arrival.Delay.in.Minutes", "satisfaction"
               )
airline_df <- airline_df[, col_order]

# drop columns
drop_col <- c("Gender", "Customer.Type", "Type.of.Travel", "Class",
              "Inflight.wifi.service", "Food.and.drink", "Seat.comfort")
airline_df[, drop_col] <- list(NULL)

# rename columns
old_colnames <- c("Gender.C", "Customer.Type.C", "Type.of.Travel.C", "Class.C", 
                  "Inflight.wifi.service.C", "Food.and.drink.C", "Seat.comfort.C"
                  )
new_colnames <- drop_col
setnames(airline_df, old = old_colnames, new = new_colnames)

# drop X column
airline_df[, "X"] <- list(NULL)
```

## Analyses

### Customer Gender

```{r include = FALSE, warning = FALSE}
#2a customer gender by customer type- table
cs_gender_cust_type_df <- airline_df %>%
  group_by(Gender, Customer.Type) %>%
  summarise(counts = n())

#3a customer gender by customer type and type of travel- table
cs_gender_cust_type_travel_df <- airline_df %>%
  group_by(Gender, Customer.Type, Type.of.Travel) %>%
  summarise(counts = n())

#4a customer gender by type of travel and class- table
cs_gender_travel_class_df <- airline_df %>%
  group_by(Gender, Type.of.Travel, Class) %>%
  summarise(counts = n())

#5a Create age group
airline_df["age_group"] = cut(airline_df$Age, c(0, 10, 20, 30, 40, 50, 60, 70, 80, Inf), c("0-10", "11-20", "21-30","31-40","41-50","51-60","61-70","71-80", ">80"), include.lowest=TRUE)

#5b customer gender by age group and customer type- table
cs_gender_age_type_df <- airline_df %>%
  group_by(Gender, age_group,Customer.Type) %>%
  summarise(counts = n())

#6b customer gender by satisfaction- table
cs_gender_satisfied_df <- airline_df %>%
  group_by(Gender, satisfaction) %>%
  summarise(counts = n())

#6d customer gender by age group and satisfaction- table
cs_gender_age_satisfied_df <- airline_df %>%
  group_by(Gender, age_group, satisfaction) %>%
  summarise(counts = n())
```

```{r echo = FALSE, warning = FALSE}
#2b customer gender by customer type- graph
cs_gender_cust_type_g <- 
  ggplot(cs_gender_cust_type_df, 
         aes(x = Customer.Type,
             y = counts)) + 
  geom_bar(stat='identity', position = "dodge") +
  labs(x = "Customer Type", y = "Frequency") + 
  facet_wrap(~Gender) +
  scale_fill_brewer(palette="Spectral")+ 
  ggtitle("Customer Type by Gender in Train Dataset")
cs_gender_cust_type_g

#3b customer gender by customer type and type of travel- graph
cs_gender_cust_type_travel_g <- 
  ggplot(cs_gender_cust_type_travel_df, 
         aes(x = Customer.Type,
             y = counts, 
             fill = Type.of.Travel)) + 
  geom_bar(stat='identity', position = "dodge") +
  labs(x = "Customer.Type", y = "Frequency") + 
  facet_wrap(~Gender) +
  scale_fill_brewer(palette="Spectral")+ 
  ggtitle("Customer Type by Gender and Travel Type in Train Dataset")
cs_gender_cust_type_travel_g

#4b customer type by type of travel and class- graph
cs_gender_travel_class_g <- 
  ggplot(cs_gender_travel_class_df, 
         aes(x = Type.of.Travel,
             y = counts, 
             fill = Class)) + 
  geom_bar(stat='identity', position = "dodge") +
  labs(x = "Type of Travel", y = "Frequency") + 
  facet_wrap(~Gender) +
  scale_fill_brewer(palette="Spectral")+ 
  ggtitle("Customer Type by Travel Type and Class in Train Dataset")
cs_gender_travel_class_g

#5c customer gender by age group and customer type- graph
cs_gender_age_type_g <- 
  ggplot(cs_gender_age_type_df, 
         aes(x = age_group,
             y = counts,
             fill = Customer.Type)) + 
  geom_bar(stat='identity', position = "dodge") +
  labs(x = "age_group", y = "Frequency") + 
  facet_wrap(~Gender) +
  scale_fill_brewer(palette="Spectral")+ 
  ggtitle("Customer Type by Gender and Age Group in Train Dataset")
cs_gender_age_type_g

#6a Satisfaction count graph
satisfaction_count <- airline_df %>% 
  count(satisfaction) %>% 
  ggplot(aes(x = satisfaction, y = n, fill = satisfaction)) +
  geom_bar(stat = "identity", colour = "black", alpha = 0.75) +
  geom_text(aes(label = n), 
                position=position_dodge(width=0.9), 
                vjust=-0.5) + 
  ylim(0, 60000) + 
  labs(y = "Count") + 
  scale_fill_brewer(palette="Spectral") + 
  ggtitle("Satisfaction variable in Train Dataset")
satisfaction_count
  
#6c customer gender by satisfaction- graph
cs_gender_satisfied_g <- 
  ggplot(cs_gender_satisfied_df, 
         aes(x = satisfaction,
             y = counts)) + 
  geom_bar(stat='identity', position = "dodge") +
  labs(x = "satisfaction", y = "Frequency") + 
  facet_wrap(~Gender) +
  scale_fill_brewer(palette="Spectral") + 
  ggtitle("Satisfaction by Gender in Train Dataset")
cs_gender_satisfied_g
  
#6e customer gender by age group and satisfaction- graph
cs_gender_age_satisfied_g <- 
  ggplot(cs_gender_age_satisfied_df, 
         aes(x = satisfaction,
             y = counts,
             fill = age_group)) + 
  geom_bar(stat='identity', position = "dodge") +
  labs(x = "satisfaction", y = "Frequency") + 
  facet_wrap(~Gender) +
  scale_fill_brewer(palette="Spectral") + 
  ggtitle("Satisfaction by Gender and Age Group in Train Dataset")
cs_gender_age_satisfied_g

#7 age histogram
age_hist<- ggplot(data = airline_df, aes( x = Age)) + 
  geom_density(fill="navy blue", color="black", alpha=0.75) +
  labs(title = "Distribution of Age", 
       subtitle = "Airline Passenger Satisfaction")
age_hist
```

### Customer Type
```{r include = FALSE, warning = FALSE}
# customer type
cs_type_df <- airline_df %>%
  group_by(Customer.Type) %>%
  summarise(counts = n()) %>% 
  mutate(perc = counts / sum(counts)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

# customer type by type of travel and class
cs_type_travel_class_df <- airline_df %>%
  group_by(Customer.Type, Type.of.Travel, Class) %>%
  summarise(counts = n())

# customer type by satisfaction
cs_type_satisfaction_df <- airline_df %>%
  group_by(Customer.Type, satisfaction) %>%
  summarise(counts = n())

# customer type by satisfaction and satisfaction level in each factors
cs_type_satisfaction_lvl_df <- airline_df[c(3,8:21,24)]
cs_type_satisfaction_lvl_df <- 
  cs_type_satisfaction_lvl_df %>% 
  pivot_longer(-c(Customer.Type, satisfaction),
               names_to = "factors",
               values_to = "satisfaction.level")  %>%
  group_by(Customer.Type, satisfaction, factors, satisfaction.level) %>%
  summarise(counts = n())
```

```{r echo = FALSE, warning = FALSE}
# customer type
cs_type_g <- 
  ggplot(cs_type_df, 
         aes(x = "",
             y = perc, 
             fill = Customer.Type)) + 
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  guides(fill=guide_legend(title="Customer Type")) +
  geom_text(aes(label = labels), 
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  scale_fill_brewer(palette="Spectral") +
  labs(title = "Customer Type") +
  theme_void()
cs_type_g

# customer type by type of travel and class
cs_type_travel_class_g <- 
  ggplot(cs_type_travel_class_df, 
         aes(x = Type.of.Travel,
             y = counts, 
             fill = Class)) + 
  geom_bar(stat='identity', position = "dodge") +
  labs(title = "Customer Type by Type of Travel and Class",
       x = "Type of Travel",
       y = "Frequency") + 
  facet_wrap(~Customer.Type) +
  scale_fill_brewer(palette="Spectral")
cs_type_travel_class_g

# customer type by gender and age
cs_type_gender_age_g <-
  ggplot(airline_df, 
         aes(x = Gender,
             y = Age,
             fill = Gender,
             color = Gender)) + 
  geom_violin(width = 0.3, position = position_dodge())+
  geom_boxplot(width = 0.1, color = "black", alpha = 0.2) +
  labs(title = "Customer Type by Gender and Age", 
       x = "Gender",
       y = "Age") + 
  facet_wrap(~Customer.Type) +
  scale_fill_brewer(palette="Spectral")
cs_type_gender_age_g

# Flight distance by customer type and class
cs_type_flight_d_g <- 
  ggplot(airline_df, 
         aes(x = Flight.Distance,
             fill = Customer.Type)) +
  geom_density(alpha = 0.3) +
  labs(title = "Flight Distance by Customer Type and Class",
       y = "Flight Distance", 
       x = "Customer Type") + 
  guides(fill=guide_legend(title="Customer Type")) +
  facet_grid(Class ~ .) + 
  scale_fill_brewer(palette = "Spectral")
cs_type_flight_d_g

# Customer Type by satisfaction
cs_type_satisfaction_g <- 
  ggplot(cs_type_satisfaction_df, 
         aes(x = satisfaction,
             y = counts, 
             fill = satisfaction)) + 
  geom_bar(stat='identity', position = "dodge", width = 0.5) +
  guides(fill=guide_legend(title="Satisfaction")) +
  labs(title = "Satisfaction by Customer Type",
       x = "Satisfaction",
       y = "Frequency") + 
  facet_wrap(~Customer.Type) +
  scale_fill_brewer(palette="Spectral")
cs_type_satisfaction_g
```

```{r echo = FALSE, warning = FALSE, fig.height = 20, fig.width = 12}
# Customer type by satisfaction and satisfaction level in each factors
cs_type_satisfaction_lvl_g <- 
  ggplot(cs_type_satisfaction_lvl_df, 
         aes(x = satisfaction.level,
             y = counts, 
             fill = satisfaction)) + 
  geom_bar(stat='identity', position = "dodge") +
  labs(title = "Customer Type by satisfaction and satisfaction level in each factors",
       x = "Satisfaction Level",
       y = "") + 
  facet_grid(factors~Customer.Type) +
  scale_fill_brewer(palette="Spectral")
cs_type_satisfaction_lvl_g
```

# Results

# Conclusion
